# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-02 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=50)),
                ('ticker', models.CharField(default='NEWSFLASH', max_length=1000)),
                ('address', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('info', models.TextField(blank=True, max_length=200)),
                ('sales_phone', models.CharField(blank=True, max_length=200)),
                ('bkg_phone', models.CharField(blank=True, max_length=200)),
                ('salse_email_1', models.EmailField(blank=True, max_length=30)),
                ('salse_email_2', models.EmailField(blank=True, max_length=30)),
                ('logo', models.ImageField(upload_to='logos')),
            ],
        ),
    ]
